function data = ImportTextFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  data = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  data = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  data = importfile("D:\chatGPT-app-projects\RCSA\Draft\data\FRF_YY_3_short_tool_holder.txt", [85, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Sep-2026 10:55:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [85, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2", "VarName3"];
opts.SelectedVariableNames = ["VarName2", "VarName3"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName2", "VarName3"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName2", "VarName3"], "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data);
end